apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  host: k8s-poc-prometheus.devopscheats.com
  # tls:
  #   secret: prometheus-secret
  upstreams:
  - name: prometheus
    service: prometheus-service
    port: 8000
    # fail-timeout: 10s
    # max-fails: 1
    # max-conns: 32
    # keepalive: 32
    # connect-timeout: 30s
    # read-timeout: 30s
    # send-timeout: 30s
    # next-upstream: "error timeout non_idempotent"
    # next-upstream-timeout: 5s
    # next-upstream-tries: 10
    # client-max-body-size: 2m
  routes:
  - path: /
    action:
      pass: prometheus